# Generated by Django 6.0.2 on 2026-02-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('rssi', models.IntegerField(default=0)),
                ('location', models.IntegerField(blank=True, choices=[(0, 'Attic'), (1, 'Crawlspace'), (2, 'Basement'), (3, 'Other')], db_index=True, help_text='V4: DIP-derived location (0=Attic, 1=Crawlspace, 2=Basement, 3=Other).', null=True)),
                ('temp_c', models.FloatField(blank=True, null=True)),
                ('hum_pct', models.FloatField(blank=True, null=True)),
                ('press_hpa', models.FloatField(blank=True, null=True)),
                ('batt_mv', models.IntegerField(default=0)),
                ('flags', models.IntegerField(default=0)),
                ('seq', models.IntegerField(db_index=True, default=0)),
                ('motion0', models.BigIntegerField(default=0)),
                ('motion1', models.BigIntegerField(default=0)),
                ('batt_pct', models.IntegerField(blank=True, null=True)),
                ('uptime_min', models.IntegerField(blank=True, null=True)),
                ('dew_point_c', models.FloatField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['-created_at'], name='monitor_rea_created_878ed1_idx'), models.Index(fields=['source', '-created_at'], name='monitor_rea_source_14251d_idx'), models.Index(fields=['source', 'seq'], name='monitor_rea_source_eb865a_idx'), models.Index(fields=['location', '-created_at'], name='monitor_rea_locatio_b47223_idx')],
            },
        ),
    ]
